### PR TITLE
Reduce padding of the footer class

### PR DESCRIPTION
**Pull request by lapostoj**

### CODE REVIEW

**Review by StevePole — CHANGES_REQUESTED** [review]
Not so keen on this approach for footer.  All of the main spacing classes are responsive.  I would expect this to use the -mobile, -tablet and -desktop sizes of either spacing-1 or spacing-2.

**Comment by lapostoj** [comment]
Yes makes sense, updated 🙂

**Review by StevePole — APPROVED** [review]
👍

**Comment by StevePole** [comment]
Actually, one final thought, should footer have a small amount of padding-bottom?  It could be flush with the bottom of the screen at the moment.

**Comment by lapostoj** [comment]
The "problem" is that it already have 24px du to ending with a <p> so didn't feel like adding more...
But maybe the right way is to have some padding in the footer and give a margin 0 to that <p>

What do you think?

**Comment by StevePole** [comment]
Probably fine to rely on the last element.  Footer will likely contain either a list or paragraph, both of which 24px margin underneath

**Pull request merged**
