### PR TITLE
Navbar improvements

### PR DESCRIPTION
**Pull request by nabaroa**
Added active styles to navbar buttons and updated to dropdown item styles.

image

image

### CODE REVIEW

**Review by matallo — APPROVED** [review]
LGTM, screenshots from the mobile version? 😄

**Comment by nabaroa** [comment]
## Active item styles 
Added semibold.
ezgif com-video-to-gif 5

**Comment by nabaroa** [comment]
## Fix style gap onMouseDown on mobile

When mouse down/touch on mobile we show the desktop styles for 1 second. 
The reason is because the `focus-within` class takes some time to add. I've fixed it changing the mobile dropdown styles with the mediaquery change and not with the focus-within.

** before **
image

** after **
ezgif com-video-to-gif 6

**Comment by nabaroa** [comment]
## Dot badge on mobile

In some languages the badge takes to much space. The solution is to adapt the badge in mobile to a green dot.

ezgif com-video-to-gif 7

**Comment by nabaroa** [comment]
## Disable mobile callouts

When a target is touched and held on iPhone OS, Safari displays a callout information about the link. This property allows disabling that behavior.

image

**Review by matallo — APPROVED** [review]
didn't know about `-webkit-touch-callout` cool! 👍

**Comment by nabaroa** [comment]
## Allow right arrow with pull-xs-right

When logged the right navigation is created by pull-xs-right

**Before**
image

**After**
image

The arrow position is correct for the default padding. Must change the spacing utilities on markup to align the caret with the arrow

**Comment by nabaroa** [comment]
Demo: https://kind-dingo-36.localtunnel.me/examples/nested-navbar/

**Review by matallo — APPROVED** [review]

**Pull request merged**
