### PR TITLE
Add secondary navigation

### PR DESCRIPTION
**Pull request by nabaroa**
# v5.16.0

## Add secondary navigation

[Demo](https://selfish-gecko-69.localtunnel.me/components/#navbar-secondary)
[The designs](https://transferwise.invisionapp.com/share/SRFMQL4H9EB#/screens/276982891_foldout_Top_Nav_Rollout_Plan)

image

Added `.navbar-title-link` class to secondary nav title link.

### CODE REVIEW

**Comment by matallo** [comment]
Awesome! Looking forward to integrate this in the different products.

I found the mobile view looks a bit weird, though.

screen shot 2018-05-09 at 14 25 55

Also, what's the rationale behind creating a demo page for a component (i.e. nested navbar)? Shall we create one for this too?

**Review by matallo — CHANGES_REQUESTED** [review]
Awesome! Looking forward to integrate this in the different products.

I found the mobile view looks a bit weird, though.

screen shot 2018-05-09 at 14 25 55

Also, what's the rationale behind creating a demo page for a component (i.e. nested navbar)? Shall we create one for this too?

**Comment by nabaroa** [comment]
I created a demo page in the nested navbar because it was necessary to show the mobile version. In this case the secondary nav only relates to desktop screens. But I will create an example page for this one also so we can have the complete picture. 

I´ll have a look to that issue in mobile.

**Comment by nabaroa** [comment]
@matallo Added the example page: https://stupid-ape-75.localtunnel.me/examples/navbar-secondary/
How can I replicate that issue on mobile? In the example works correctly

**Comment by nabaroa** [comment]
Updated demo: https://selfish-gecko-69.localtunnel.me/components/#navbar-secondary

**Review by matallo — APPROVED** [review]

**Pull request merged**
